#!/bin/sh

###
# Copyright (C) 2010: Fabián E. Gallina
# Contact list: fabian@gnu.org.ar
# Version 0.1
#
# This file is part of HATE ((X)HTML from (B)Ash Template Engine)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###

hate_variables=''
hate_template=''

# Exits and prints the correct error message
#
# @param $1 the error number
# @param $2 optional the object to print
# @return the error number
hate_error () {
    echo -n "error #$1: "
    case $number in
        1)
            echo "template not especified"
            ;;
        2)
            echo "template $2 does not exist."
            ;;
        3)
            echo "include $2 does not exist."
            ;;
        *)

    esac
    
    exit $1
}

# Assigns variables for template
#
# @param $1 the variable name
# @param $2 the variable value
# @return nothing, it modifies the global `hate_variables' var.
hate_assign () {
    hate_variables=$hate_variables$1':'$2','
}

# Cleans non replaced variable tags
#
# @return nothing, updates `hate_template' global var.
hate_cleanup_tags () {
    # FIXME: evaluate if a config var should disable this
    hate_template=$(echo $hate_template | sed "s/{{[^}][^}]*}}//g")
}

# Takes care of parsing for tags as the following:
#
# {% for1 i in "magic blah bleh"; delete_trailing:"," %}
#     {{$i}},
# {% endfor1 %}
#
# This will result in
# magic, blah, bleh
#
# Note that everything after ; is optional and to retrieve the
# index variable you'll need to prepend a dollar sign ($) to the
# variable. This has been made in order to avoid collisions with
# standard variables.
#
# @return nothing, it modifies the `hate_template' global var.
hate_parse_for () {
    local regex=""
    local tag=""
    local contents=""
    local index=""
    local elements=""
    local trailing=""
    local pre=""
    local post=""
    local parsed=""
    local trailing_index=0
    local trailing_maybe=""

    regex="\{% *for([0-9]+) +([a-z0-9]+) +in +\"[^\"]+\" *;"
    regex=$regex"( *delete_trailing:\"[^%]\")?"
    regex=$regex" *%\}.*\{\{\\$\2\}\}.*\{% endfor\1 %\}"

    while [ true ]; do
        parsed=""
        tag=$(echo $hate_template | egrep -o "$regex" | awk "NR>1{exit};1")

        if [ "$tag" ]; then
            contents=$(echo $tag | sed "s/[^%]*%}\|{%[%]*//g")
            index=$(echo $tag | sed "s/{% *for[0-9][0-9]*  *\|  *in.*//g")
            elements=$(echo $tag | sed "s/{% *for[0-9][0-9]*  *[a-z0-9][a-z0-9]*  *in  *\"\|\" *;.*//g")
            trailing=$(echo $tag | awk -F 'delete_trailing:\"|\" *%}' '{print $2}')
            pre=$(echo $contents | sed "s/{{\$$index}}.*//")
            post=$(echo $contents | sed "s/.*{{\$$index}}//")

            for element in $elements; do
                parsed=$parsed$pre$element$post
            done

            if [ "$trailing" ]; then
                trailing_index=$((${#parsed} - ${#trailing}))
                trailing_maybe=${parsed:$trailing_index}
                parsed=${parsed:0:$trailing_index}${trailing_maybe/"$trailing"/""}
            fi
            hate_template=${hate_template/"$tag"/"$parsed"}
        else
            break
        fi

    done
}

# Handles all include tags with the form {% include file.html %}.
#
# @return nothing, updates `hate_template' global var.
hate_parse_includes () {
    local tag=""
    local file=""
    while [ true ]; do
        tag=$(echo $hate_template | egrep -o "\{% *include +[^%]+ *%}" | awk "NR>1{exit};1")
        if [ "$tag" ]; then
            file=$(echo $tag | sed "s/{% *include  *\| *%}//g")
            if [ -e "$file" ]; then
                false
            else
                hate_error 3 "$file"
            fi
            contents=$(cat $file)
            hate_template=${hate_template/"$tag"/"$contents"}
        else
            break
        fi
    done
}

# Handles all variable tags with the form {{varname}}.
#
# @param $1 the var name
# @param $2 the var value
# @return nothing, updates `hate_template' global var.
hate_parse_var () {
    hate_template=$(echo ${hate_template//$(echo '{{'$1'}}')/"$2"})
}

# This is the main entry point to the template system.
#
# @param $1 the template filename
# @return the parsed `hate_template' global var.
hate_render () {
    local variable=""
    local value=""
    local parsed=""

    if [ -z "$1" ]; then
        hate_error 1
    fi

    if [ -e "$1" ]; then
        false
    else
        hate_error 2 "$1"
    fi

    hate_template=$(cat "$1")

    hate_parse_includes

    while [ "$hate_variables" ]; do
        variable=$(echo "$hate_variables" | awk -F ":|," '{print $1}')
        value=$(echo "$hate_variables" | awk -F ":|," '{print $2}')
        parsed=$(echo "$hate_variables" | awk -F "," '{print $1}')
        hate_variables=$(echo "$hate_variables" | sed "s/$parsed, *//g")
        hate_parse_var "$variable" "$value"
    done

    hate_parse_for
    hate_cleanup_tags
    echo $hate_template
}